# Generated by Django 5.1.7 on 2025-03-20 02:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('unavailable_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)])),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_id', 'unavailable_date'], name='calendar_ap_product_19a8c0_idx')],
                'unique_together': {('product_id', 'unavailable_date')},
            },
        ),
    ]
